### ISSUE TITLE
Versions in the configurator

### ISSUE THREAD

**Issue by mnieke** [DarwinSPL/DarwinSPL#67]
Some minor bugs in the editor concerning versions:
1) The selected version of a feature does not always appear directly under the feature on the right-hand side view. Scenario in this case: Select "RootFeature", then "New Feature 1", then "V0" -> it looks like V0 of "New Feature 1" is selected.
![grafik](https://user-images.githubusercontent.com/5243830/33018105-56accd6e-cdf5-11e7-8d32-597999343ea9.png)

2) I can select versions without their features: select the feature and the version. Then deselect the feature.
![grafik](https://user-images.githubusercontent.com/5243830/33018160-8f277310-cdf5-11e7-9bc7-16861c57e8f4.png)
All versions should be automatically deselected when the corresponding feature is deselected.

**Comment by mnieke** [comment]
I still have this issue.
If I deselect the feature, the versions also disappears on the overview on the right panel.
But it is still selected (orange box behind it and if I save the configuration).

**Comment by alahola** [comment]
@mnieke Hopefully the issue is fixed now :D 
One question. On selection of the feature should any version be automatically selected?

![image](https://user-images.githubusercontent.com/22443385/34103750-2f81c6fe-e3ee-11e7-8e38-fa874e5b7ccb.png)
On selection of the feature (currently)

![image](https://user-images.githubusercontent.com/22443385/34103726-1ee8469c-e3ee-11e7-941e-7f3345b64cbb.png)

**Comment by mnieke** [comment]
Yes, this looks good! Thank you :)
